name: CI Pipeline


# run when pushed to main to main and when the 
# pull request targets the main branches 
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # step 1: download the code onto GibtHub VM
            - name: Checkout repository
              uses: actions/checkout@v4

            # install Python on GitHub VM
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.14"
                cache: "pip"
            
            # install project's dependencies
            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install framework tests
              run: pip install -r requirements_dev.txt

            # sintax check
            - name: Check Python syntax
              run: |
               python -m py_compile main.py
               python -m py_compile utils.py
               echo "All files passed syntax check"

            # lint the code using flake8 to check code style and issues
            - name: Lint with flake8
              run: flake8 . --max-line-length=120 --exclude=.git

            # functions test from utils.py with pytest framework
            - name: Run pytest
              run: pytest test_utils.py -v

        